name: CD

on:
  release:
    types: [ "created" ]

  

jobs:
  cd:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: check package versio
        run: |
          if [ "v${{ steps.package-version.outputs.current-version }}" != "${{github.ref_name}}" ]; then
            echo "Tag version and package version should be same"
            exit 1
          fi
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}