name: CD

on:
  release:
    types: [ "created" ]

  

jobs:
  cd:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: debug
        run: echo ${{steps.package-version.outputs.current-version}}
      - name: debug
        run: echo ${{github.ref_name}}
      - name: check package versio
        if: ${{format('v{}', steps.package-version.outputs.current-version) != github.ref_name}}
        run: exit 1
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}