name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  ci:
    name: Build on ${{ matrix.os }} with NodeJs ${{ matrix.node-version }}
    strategy:
        matrix:
            os: ['windows-latest', 'ubuntu-latest']
            node-version: ['14.x', '16.x', '18.x']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Check eslint
        run: npm run lint
      - name: Check prettier
        run: npx prettier './src/*' -w
      - name: Build
        run: npm run build