name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  ci:
    name: Build on ${{ matrix.os }} with NodeJs ${{ matrix.node-version }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            node-version: [14, 16, 18]
            include:
            - node-version: 14
              npm: 7

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: install npm
        if: ${{ matrix.npm }}
        run: npm install -g npm@${{ matrix.npm }}
      - name: Install npm dependencies
        run: npm ci
      - name: Check eslint
        run: npm run lint
      - name: Check prettier
        run: npx prettier './src/*' -l
      - name: Build
        run: npm run build